name: Deploy to Linux Server

on:
  push:
    branches:
      - main  # Triggers the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Match this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the Docker image
      run: docker build -t my-node-app .

    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
        scp -o StrictHostKeyChecking=no my-node-app.tar.gz $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
        ssh $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && docker load -i my-node-app.tar.gz && docker-compose up -d"
